version: 2
updates:
- package-ecosystem: gomod
  directory: "/components/cmd"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependencies/updates
  reviewers:
  - xzyaoi
  ignore:
  - dependency-name: github.com/getsentry/sentry-go
    versions:
    - 0.10.0
    - 0.9.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.8.0
  - dependency-name: github.com/google/uuid
    versions:
    - 1.1.5
    - 1.2.0
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
  - dependency-name: github.com/ilibs/gosql/v2
    versions:
    - 2.1.0
  - dependency-name: github.com/mattn/go-sqlite3
    versions:
    - 1.14.6
  - dependency-name: github.com/prometheus/client_golang
    versions:
    - 1.9.0
- package-ecosystem: npm
  directory: "/components/dashboard"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependencies/updates
  reviewers:
  - xzyaoi
  ignore:
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.10
    - 4.5.11
  - dependency-name: codemirror
    versions:
    - 5.59.1
    - 5.59.2
  - dependency-name: dayjs
    versions:
    - 1.10.3
    - 1.10.4
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.10
    - 4.5.11
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.10
    - 4.5.11
  - dependency-name: electron
    versions:
    - 10.2.0
    - 11.2.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: ini
    versions:
    - 1.3.8
- package-ecosystem: npm
  directory: "/components/discovery"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependencies/updates
  reviewers:
  - xzyaoi
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.21
    - 14.14.22
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.5
    - 7.6.7
  - dependency-name: mongoose
    versions:
    - 5.11.12
    - 5.11.14
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.5
    - 7.6.7
  - dependency-name: helmet
    versions:
    - 4.4.0
    - 4.4.1
  - dependency-name: "@nestjs/cli"
    versions:
    - 7.5.4
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.16
    - 26.0.20
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.3
  - dependency-name: ini
    versions:
    - 1.3.8
- package-ecosystem: pip
  directory: "/components/mlserve"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependencies/updates
  reviewers:
  - xzyaoi
  ignore:
  - dependency-name: pillow
    versions:
    - 8.1.0
  - dependency-name: uvicorn
    versions:
    - 0.13.3
    - 0.13.4
  - dependency-name: readme-renderer
    versions:
    - "29.0"
  - dependency-name: twine
    versions:
    - 3.3.0
  - dependency-name: secretstorage
    versions:
    - 3.3.0
    - 3.3.1
  - dependency-name: keyring
    versions:
    - 21.8.0
    - 22.0.1
    - 22.3.0
  - dependency-name: cffi
    versions:
    - 1.14.5
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.58.0
  - dependency-name: cryptography
    versions:
    - 3.3.1
    - 3.3.2
  - dependency-name: bleach
    versions:
    - 3.3.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: requests
    versions:
    - 2.25.1
  - dependency-name: numpy
    versions:
    - 1.19.5
